from pathlib import Path

from logids.correlation import correlate_findings
from logids.detector import detect, load_config
from logids.evaluation import evaluate_findings, load_labels
from logids.matchers import brute_force_match, build_prefix_table, kmp_match
from logids.parser import parse_log_file


ROOT = Path(__file__).resolve().parents[1]


def test_kmp_matches_brute_force():
    text = "normal request union select password from users"
    pattern = "union select"
    assert brute_force_match(text, pattern).matched
    assert kmp_match(text, pattern, build_prefix_table(pattern)).matched
    assert not kmp_match(text, "not-present").matched


def test_parser_keeps_valid_and_counts_invalid():
    records, stats = parse_log_file(ROOT / "data" / "sample_access.log")
    assert stats.total >= 45
    assert stats.valid >= 40
    assert stats.invalid == 1
    assert any(record.format_name == "common_access" for record in records)
    assert any(record.format_name == "key_value" for record in records)
    assert any(record.format_name == "json" for record in records)


def test_detector_finds_main_attack_classes():
    records, _ = parse_log_file(ROOT / "data" / "sample_access.log")
    config = load_config(ROOT / "config" / "rules.json")
    findings = detect(records, config)
    types = {item.finding_type for item in findings}
    assert "SQL_INJECTION" in types
    assert "XSS" in types
    assert "PATH_TRAVERSAL" in types
    assert "COMMAND_INJECTION" in types
    assert "BRUTE_FORCE" in types
    assert "PORT_SCAN" in types
    assert "REQUEST_BURST" in types
    assert "BLACKLIST" in types
    assert "OBFUSCATED_PAYLOAD" in types


def test_correlation_produces_scored_incidents():
    records, _ = parse_log_file(ROOT / "data" / "sample_access.log")
    config = load_config(ROOT / "config" / "rules.json")
    findings = detect(records, config)
    incidents = correlate_findings(findings)
    assert incidents
    assert incidents[0].score >= incidents[-1].score
    assert any("SQL_INJECTION" in incident.finding_types for incident in incidents)


def test_corpus_evaluation_is_realistic():
    """The large labeled corpus must give a strong but non-perfect score, and
    must contain honest false positives and false negatives by design."""
    corpus = ROOT / "data" / "corpus_access.log"
    labels_csv = ROOT / "data" / "corpus_labels.csv"
    if not corpus.exists() or not labels_csv.exists():
        return  # corpus is generated by scripts/build_corpus.py
    records, stats = parse_log_file(corpus)
    assert stats.valid > 1000
    config = load_config(ROOT / "config" / "rules.json")
    findings = detect(records, config)
    metrics = evaluate_findings(findings, load_labels(labels_csv))
    assert 0.85 <= metrics.f1 <= 1.0
    assert metrics.fp > 0 and metrics.fn > 0  # evaluation is honest, not over-fitted
